# Generated by Django 2.2.1 on 2019-05-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('case_price', models.IntegerField()),
                ('case_size', models.IntegerField()),
                ('vintage', models.IntegerField(max_length=4)),
                ('image', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
