# Generated by Django 2.2.1 on 2019-05-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_auto_20190516_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='varietal',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
