# Generated by Django 2.2.1 on 2019-05-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_wine_varietal'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='country',
            field=models.CharField(default='Italy', max_length=50),
        ),
        migrations.AlterField(
            model_name='wine',
            name='case_size',
            field=models.IntegerField(choices=[(6, 6), (12, 12)], default=12),
        ),
        migrations.AlterField(
            model_name='wine',
            name='size',
            field=models.CharField(choices=[('375mL', '375mL'), ('750mL', '750mL'), ('1.5L', '1.5L')], default='750mL', max_length=5),
        ),
    ]
