# Generated by Django 2.2.1 on 2019-05-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0005_auto_20190516_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='bottle_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
