# Generated by Django 2.2.1 on 2019-05-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0006_wine_bottle_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='bottle_price',
        ),
    ]
